version: '3.9'
services:
  trooper-ms-account:
    container_name: ms-account
    build: ./
    ports:
      - 3002:3002
    volumes:
      - ./:/app/ms-account
    environment:
      - JWT_SECRET=MTk4OGExOTZkMWYyOWZjZjlmOTcwMWVjZWRjMzc1MzZkOGM0MmFjMjQ0NjcyZjIzZDQwOGU4YTQ1YWQ3NTRjZA==
    depends_on:
      - mongodb-ms-account

  mongodb-ms-account:
    image: mongo:5
    ports:
      - 27019:27017
    volumes:
      - mongodb-account-volume-docker:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=secret

  mongodb-ms-account-test:
    image: mongo:5
    ports:
      - 27020:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=secret

volumes:
  mongodb-account-volume-docker:

networks: 
  default:
    name: trooper-network
    external: true